server:
  port: 8082

spring:
  application:
    name: AUTH-SERVICE

  datasource:
    url: jdbc:postgresql://localhost:5435/user_db
    username: vitya
    password: 22817
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


openapi:
  service:
    title: auth-service doc
    version: 1.0.0
    url: http://localhost:8000


springdoc:
  api-docs:
    path: /auth-service/v3/api-docs
  swagger-ui:
    path: /auth-service/swagger-ui.html