volumes:
  pg_data:
  pg_data_2:
  pg_data_3:


services:
  library_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: vitya
      POSTGRES_PASSWORD: 22817
      POSTGRES_DB: library_db
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  book-service:
    build: ./book-service
    restart: always
    depends_on:
      - library_db
      - eureka-registry
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://library_db:5432/library_db
      SPRING_DATASOURCE_USERNAME: vitya
      SPRING_DATASOURCE_PASSWORD: 22817
      SERVER_PORT: 8080
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-registry:8761/eureka/

  library_db_2:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: vitya
      POSTGRES_PASSWORD: 22817
      POSTGRES_DB: library_db_2
    volumes:
      - pg_data_2:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  library-service:
    build: ./library-service
    restart: always
    depends_on:
      - library_db_2
      - eureka-registry
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://library_db_2:5432/library_db_2
      SPRING_DATASOURCE_USERNAME: vitya
      SPRING_DATASOURCE_PASSWORD: 22817
      SERVER_PORT: 8081
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-registry:8761/eureka/


  user_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: vitya
      POSTGRES_PASSWORD: 22817
      POSTGRES_DB: user_db
    volumes:
      - pg_data_3:/var/lib/postgresql/data
    ports:
      - "5435:5432"

  auth-service:
    build: ./auth-service
    restart: always
    depends_on:
      - user_db
      - eureka-registry
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://user_db:5432/user_db
      SPRING_DATASOURCE_USERNAME: vitya
      SPRING_DATASOURCE_PASSWORD: 22817
      SERVER_PORT: 8082
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-registry:8761/eureka/

  eureka-registry:
    build: ./eureka-registry
    restart: always
    ports:
      - "8761:8761"
    environment:
      SERVER_PORT: 8761


  api-gateway:
    build: ./api-gateway
    restart: always
    depends_on:
      - eureka-registry
    ports:
      - "8000:8000"
    environment:
      SERVER_PORT: 8000
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-registry:8761/eureka/

