server:
  port: 8000

spring:
  cloud:
    gateway:
      routes:
        - id: book-service
          uri: lb://BOOK-SERVICE
          predicates:
            - Path=/books/**
          filters:
            - AuthenticationFilter

        - id: library-service
          uri: lb://LIBRARY-SERVICE
          predicates:
            - Path=/library/**
          filters:
            - AuthenticationFilter

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**


  application:
    name: API-GATEWAY


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

