server:
  port: 8080

spring:
  application:
    name: BOOK-SERVICE

  datasource:
    url: jdbc:postgresql://localhost:5433/book_db
    username: vitya
    password: 22817
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

openapi:
  service:
    title: book-service doc
    version: 1.0.0
    url: http://localhost:8000


springdoc:
  api-docs:
    path: /book-service/v3/api-docs
  swagger-ui:
    path: /book-service/swagger-ui.html

#springdoc:
#  api-docs:
#    path: /v3/api-docs
#  swagger-ui:
#    path: /swagger-ui.html
#
